//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AES
{
    using System;
    using System.Collections.Generic;
    
    public partial class CASES
    {
        public int CASE_ID { get; set; }
        public string TITEL { get; set; }
        public string DESCRIPTION { get; set; }
        public string STATE { get; set; }
        public string CREATEDBY { get; set; }
        public string REQUESTERFULLNAME { get; set; }
        public string REQUESTERUSERNAME { get; set; }
        public string PHONENR { get; set; }
        public string COMPUTERNAME { get; set; }
        public Nullable<int> TIDBEREKNAD { get; set; }
        public Nullable<int> TIDSLUTFORT { get; set; }
        public System.DateTime SKAPATDEN { get; set; }
        public Nullable<System.DateTime> ANDRATDEN { get; set; }
        public string ASSIGNE { get; set; }
        public string DEPARTMENT { get; set; }
        public string KATEGORI { get; set; }
    }
}
